[package]
name = "bindgenhello"
version = "0.1.0"
authors = ["Tim Spence <timothywspence@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

